apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      containers:
        - name: slurmctld
          image: badreddine970/slurmctld-prod:latest
          command: 
            - sh
            - -c
            - |
              echo '192.168.49.1 K8s-cluster' >> /etc/hosts && gosu munge /usr/sbin/munged && exec gosu slurm /usr/sbin/slurmctld -i -Dvvv
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/slurmd
              name: test-volume
      volumes:
        - name: test-volume
          nfs:
            server: 192.168.49.1
            path: /srv/nfs/kubedata
      #     volumeMounts:
      #       - name: nfs-volume
      #         mountPath: /var/lib/slurmd
      # volumes:
      #   - name: nfs-volume
      #     persistentVolumeClaim:
      #       claimName: nfs-pvc
      hostname: slurmctld

---
apiVersion: v1
kind: Service
metadata:
  name: slurm-loadbalancer
spec:
  selector:
    app: slurmctld
  ports:
    - name: slurmctld-port
      protocol: TCP
      port: 6817
      targetPort: 6817
      nodePort: 30001
  type: LoadBalancer
