apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      containers:
        - name: slurmctld
          image: badreddine970/slurmctld-prod:latest
          command: ["sh", "-c", "gosu munge /usr/sbin/munged && exec gosu slurm /usr/sbin/slurmctld -i -Dvvv"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          volumeMounts:
            - name: slurm-state-volume
              mountPath: /tmp   # Specify the mount path inside the container
      volumes:
        - name: slurm-state-volume
          persistentVolumeClaim:
            claimName: nfs-pvc  # Specify the name of your PVC here
      hostname: slurmctld

---
apiVersion: v1
kind: Service
metadata:
  name: slurm
spec:
  selector:
    app: slurmctld
  ports:
    - name: slurmctld-port
      protocol: TCP
      port: 6817
      targetPort: 6817
      nodePort: 30001
  type: LoadBalancer
