
apiVersion: v1
kind: Pod
metadata:
  name: slurm-mysql
spec:
  hostname: slurmdbd
  containers:
    - name: mysql
      image: mariadb:10.10
      env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: slurm_acct_db
        - name: MYSQL_USER
          value: slurm
        - name: MYSQL_PASSWORD
          value: password
      # volumeMounts:
      #   - name: var-lib-mysql
      #     mountPath: /var/lib/mysql
    - name: slurmdbd
      image: badreddine970/slurmdbd:latest
      command:
        - "sh"
        - "-c"
        - |
          sed -i "s/@storagehost@/$(hostname -i)/" /etc/slurm/slurmdbd.conf
          sed -i "s/@storagehost@/$(hostname -i)/" /etc/slurm/slurm.conf   
          . /etc/slurm/slurmdbd.conf
          check_database() {
            until echo "SELECT 1" | mysql -h $StorageHost -u$StorageUser -p$StoragePass 2>&1 > /dev/null
            do
              echo "-- Waiting for database to become active ..."
              sleep 2
            done
          }
          echo "-- Checking database availability ..."
          check_database
          echo "-- Database is now active ..."
          gosu munge /usr/sbin/munged
          exec gosu slurm /usr/sbin/slurmdbd -Dvvv
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "100m"
      # volumeMounts:
      #   - name: slurm-state-volume
      #     mountPath: /tmp
  # volumes:
  #   - name: var-lib-mysql
  #     hostPath:
  #       path: /var/lib/mysql
  #       type: DirectoryOrCreate
  #   - name: slurm-state-volume
  #     persistentVolumeClaim:
  #       claimName: slurm-state-pvc